[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Add DisplayCAL directory to the Python path
pythonpath = .

# Use xunit2 for junit output
junit_family = xunit2
