[pytest]
testpaths = .
python_files = test_wexpect*.py
python_functions = test_*

# Add DisplayCAL directory to the Python path
pythonpath = ..

# Verbose output
addopts = -v --no-header

# Ignore the main conftest.py
noconftest = true

# Use xunit2 for junit output
junit_family = xunit2
